# Discord: https://discord.gg/4bAceda9q3
# Github : https://github.com/ValresMC
# By Valres
#
#
#Mine world :
world: "world"

no-break-message: "Tu ne peux rien casser içi !"
no-place-message: "Tu ne peux rien poser içi !"

regen-time: 60

blocks:
  coal_ore: 50
  diamond_ore: 50
# block_name: pourcentage
# Le pourcentage total doit être égal à 100 !
