# Discord: https://discord.gg/4bAceda9q3
# Github : https://github.com/ValresMC
# By Valres
#
#
#Mine world :
world: "world"

messages:
  no-break-message: "§cYou can break only ores here !"
  no-place-message: "§cYou can't place blocks here !"

regen-time: 60

allowed-blocks:
  - "copper_ore"
  - "iron_ore"
  - "gold_ore"
  - "redstone_ore"
  - "lapis_lazuli_ore"
  - "coal_ore"
  - "diamond_ore"
  - "emerald_ore"

blocks:
  coal_ore: 50
  diamond_ore: 50
# block_name: pourcent
