# Discord: https://discord.gg/4bAceda9q3
# Github : https://github.com/ValresMC
# By Valres
#
#
#Mine's world :
world: "world"

no-break-message: "Tu ne peux rien casser içi !"
no-place-message: "Tu ne peux rien poser içi !"

regen-time: 60
